config/routes.rb
Rails.application.routes.draw do
  devise_for :members
  resources :applicants, only: [:index, :show, :update, :delete]
  resources :members, only: [:index, :show]
  resources :discussions
  resources :categories, only: [:index, :show]
  resources :comments

  unauthenticated :member do
    devise_scope :member do
      root to: 'devise/sessions#new'
    end
  end

  authenticated :member do
    root to: 'frontpage#index', as: 'authenticated_root'
  end

  # Profile Stuff
  resource :profile, only: [:edit, :update, :show]

  # Mailboxer messages
  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
      post :restore
    end
  end
  resources :messages, only: [:new, :create]
end

app/models/discussion.rb
class Discussion < ApplicationRecord
  has_many :comments
  belongs_to :category
  belongs_to :member
end

app/controllers/discussions_controller.rb
class DiscussionsController < AuthenticatedController
  before_action :find_discussion, except: [:new, :create, :index]
  def index
    redirect_to '/'
  end

  def show
    @comments = @discussion.comments.order('created_at ASC').all.paginate(page: params[:page], per_page: 50)
    push_breadcrumb(@discussion.name, discussion_path(@discussion))
  end

  protected

  def find_discussion
    @discussion = Discussion.find(params[:id])
  end

  def initialize_breadcrumbs
    push_breadcrumb('Discussions', discussions_path)
  end
end

app/views/discussions/_discussion.html.haml
%li.list-group-item
  %h4
    = link_to discussion.name, discussion_path(discussion)
  .row
    .col-md-4.small
      %strong
        Category:
      = link_to discussion.category.name, category_path(discussion.category)
    .col-md-4.small
      %strong
        Started by:
      = link_to discussion.member.handle, member_path(discussion.member)
    .col-md-4.small
      %strong
        Comments:
      = discussion.comment_count
  .row
    .col-md-4.small
      %strong
        Last comment by
      = link_to discussion.member.handle, member_path(discussion.member)
    .col-md-4.small
      %strong
        Last active
      14 hours ago
    .col-md-4.small
      %strong New
      0

app/views/discussions/show.html.haml
= page_header @discussion.name

.row
  .col-md-3
    %p
      = link_to 'Start a new discussion', class: 'btn btn-primary btn-block'

  .col-md-9
    %ul.list-group
      = render @comments
    = will_paginate (@comments)