config/routes.rb
Rails.application.routes.draw do
  devise_for :members
  resources :applicants, only: [:index, :show, :update, :delete]
  resources :members, only: [:index, :show]
  resources :discussions
  resources :categories, only: [:index, :show]
  resources :comments

  unauthenticated :member do
    devise_scope :member do
      root to: 'devise/sessions#new'
    end
  end

  authenticated :member do
    root to: 'frontpage#index', as: 'authenticated_root'
  end

  # Profile Stuff
  resource :profile, only: [:edit, :update, :show]

  # Mailboxer messages
  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
      post :restore
    end
  end
  resources :messages, only: [:new, :create]
end

app/controllers/conversations_controller.rb
class ConversationsController < AuthenticatedController
  before_action :get_mailbox
  before_action :get_conversation, except: [:index, :empty_trash]

  def index
    get_box
    if @box.eql? "inbox"
      @conversations = @mailbox.inbox
    elsif @box.eql? "sent"
      @conversations = @mailbox.sentbox
    else
      @conversations = @mailbox.trash
    end

    @conversations = @conversations.paginate(page: params[:page], per_page: 10)
  end

  def show
    push_breadcrumb @conversation.subject.truncate(20), conversation_path(@conversation)
    @conversation.mark_as_read(current_member)
  end

  def reply
    current_member.reply_to_conversation(@conversation, params[:body])
    flash[:success] = 'Reply sent'
    redirect_to conversation_path(@conversation)
  end

  def destroy
    @conversation.move_to_trash(current_member)
    flash[:success] = 'The conversation was moved to trash.'
    redirect_to conversations_path
  end

  def restore
    @conversation.untrash(current_member)
    flash[:success] = 'The conversation was restored.'
    redirect_to conversations_path
  end

  private

  def get_mailbox
    @mailbox ||= current_member.mailbox
  end

  def get_conversation
    @conversation ||= @mailbox.conversations.find(params[:id])
  end

  def get_box
    if params[:box].blank? or !["inbox","sent","trash"].include?(params[:box])
      params[:box] = 'inbox'
    end
    @box = params[:box]
  end

  def initialize_breadcrumbs
    push_breadcrumb('Private Messages', conversations_path)
  end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
  def mailbox_section(title, current_box, opts = {})
    opts[:class] = opts.fetch(:class, '')
    opts[:class] += ' active' if title.downcase == current_box
    content_tag :li, link_to(title.capitalize, conversations_path(box: title.downcase)), opts
  end
end

app/views/conversations/_conversation.html.haml
%li.list-group-item.clearfix
  %h5
    =link_to conversation_path(conversation) do
      = conversation.subject
      - if conversation.is_unread? current_member
        %span.badge
          unread

  .btn-group-vertical.pull-right
    - if conversation.is_trashed?(current_member)
      = link_to 'Restore', restore_conversation_path(conversation), class: 'btn btn-xs btn-info', method: :post
    - else
      = link_to conversation_path(conversation), class: 'btn btn-xs btn-danger', method: :delete, data: {confirm: 'Are you sure?'} do
        %span.glyphicon.glyphicon-trash

  %p
    = render 'conversations/participants', conversation: conversation
  %p
  = conversation.last_message.body
  %small
    %span.text-muted
      = '(' + conversation.last_message.created_at.strftime("%-d %B %Y, %H:%M:%S") + ')'

app/views/conversations/_participants.html.haml
%p{ style: 'color: #777; font-style: italic;'}
  Participants:
  = (conversation.participants.reject { |x| x.id == current_member.id }).map(&:full_name).to_sentence

app/views/conversations/index.html.haml
- page_header "Private Messages"

.row
  .col-sm-3
    %p
      = link_to 'New Thread', new_message_path, class: 'btn btn-default btn-sm btn-block'
    %br

    .panel.panel-default
      .panel-heading
        %h3.panel-title Mailboxes
      .panel-body
        %ul.nav.nav-pills.nav-stacked
          = mailbox_section 'inbox', @box
          = mailbox_section 'sent', @box
          = mailbox_section 'trash', @box
  .col-sm-9                                                               |
    %ul.list-group= render partial: 'conversations/conversation', collection: @conversations
    = will_paginate

app/views/conversations/show.html.haml
- page_header 'Private Messages'

.row
  .col-xs-6
    %p
      \#{render 'conversations/participants', conversation: @conversation}
  .col-xs-6{style: 'text-align: right;'}
    = link_to 'Move to trash', conversation_path(@conversation), class: 'btn btn-danger btn-sm', method: :delete, data: {confirm: 'Are you sure?'}
.panel.panel-default
  .panel-heading
    %h3.panel-title= @conversation.subject
  .panel-body
    .messages
      - @conversation.receipts_for(current_member).order('created_at ASC').each do |receipt|
        .media
          - message = receipt.message
          .media-left
            = gravatar_for message.sender, 45, message.sender.full_name
          .media-body
            %h6.media-heading
              = message.sender.full_name
              says at #{message.created_at.strftime("%-d %B %Y, %H:%M:%S")}
            = message.body

= form_tag reply_conversation_path(@conversation), method: :post do
  .form-group
    = text_area_tag 'body', nil, cols: 3, class: 'form-control', placeholder: 'Type something...', required: true
  = submit_tag "Send Message", class: 'btn btn-primary'