config/routes.rb
Rails.application.routes.draw do
  devise_for :members
  resources :applicants, only: [:index, :show, :update, :delete]
  resources :members, only: [:index, :show]
  resources :discussions
  resources :categories, only: [:index, :show]
  resources :comments

  unauthenticated :member do
    devise_scope :member do
      root to: 'devise/sessions#new'
    end
  end

  authenticated :member do
    root to: 'frontpage#index', as: 'authenticated_root'
  end

  # Profile Stuff
  resource :profile, only: [:edit, :update, :show]

  # Mailboxer messages
  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
      post :restore
    end
  end
  resources :messages, only: [:new, :create]
end

app/views/layouts/_breadcrumbs.html.haml
- unless breadcrumbs.empty?
  %ol.breadcrumb
    %li
      = link_to 'Home', '/'
    - breadcrumbs.each do |b|
      %li
        = link_to b.title, b.path

app/views/layouts/_mail_dropdown_item.html.haml
%li
  = link_to conversation_path(conversation) do
    %h5
      = recipients
      - if conversation.is_unread? current_member
        %span.badge
          unread
    = truncate(body, length: 50)

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Enclave</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/authenticated.html.haml
!!! 5
%html
  %head
    %meta{ charset: 'utf-8' }
    %meta{ 'http-equiv' => 'X-UA-Compatible', content: 'IE=edge,chrome=1' }
    %meta{ name: 'viewport', content: 'width=device-width, initial-scale=1' }
    %title
      Forum 2.0
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'head' # Only modernizr, respond.js
    = csrf_meta_tags
  %body.authenticated
    %nav.navbar.navbar-default.navbar-fixed-top
      .container
        - # Brand and toggle get grouped for better mobile display
        .navbar-header
          %button.navbar-toggle.collapsed{ type: 'button', data: { toggle: 'collapse', target: '#bs-example-navbar-collapse-1'} }
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to 'Forum 2.0', root_path, class: 'navbar-brand'
        - # Collect the nav links, forms, and other content for toggling
        #bs-example-navbar-collapse-1.collapse.navbar-collapse
          %ul.nav.navbar-nav
            = navigation_tab 'discussions' do
              = link_to root_path, class: 'active' do
                Discussions
            = navigation_tab 'members' do
              = link_to 'Members', members_path
            = navigation_tab 'search' do
              %a{ href: '#' } Search

          %ul.nav.navbar-nav.navbar-right
            %li.dropdown
              %a.dropdown-toggle{ href: '#', 'data-toggle' => 'dropdown', role: 'button', 'aria-expanded' => 'false' }
                %span{ class: 'glyphicon glyphicon-inbox' }
                = number_badge(unseen_message_count)
              %ul.dropdown-menu
                - mailbox_conversations.each do |conversation|
                  = mail_dropdown_item(conversation)
                - if mailbox_conversations.count > 0
                  %li.divider
                %li
                  = link_to 'All messages', conversations_path

            %li.dropdown
              %a.dropdown-toggle{ href: '#', 'data-toggle' => 'dropdown', role: 'button', 'aria-expanded' => 'false' }
                = current_member.full_name
                %span.caret
              %ul.dropdown-menu{ role: 'menu' }
                %li
                  = link_to 'Your Member Page', member_path(current_member)
                %li
                  %a{ href: profile_path } Settings
                %li.divider
                %li
                  = link_to 'Log Out', destroy_member_session_path, method: :delete

    .container
      - flash.each do |type, message|
        = alert_box message, context: flash_context(type), dismissible: true unless message.blank?

      .row
        .col-md-12
          = render 'layouts/breadcrumbs', breadcrumbs: @breadcrumbs

      .row
        .col-md-12
          %h1
            = yield :page_header
      %br
      .row
        .col-md-12
          = yield

    %footer.footer
      .container
        %p
          Footer

    - # Most JS Stuff needs to be at the bottom of the body.
    - #
    - # TODO: Use Google CDN's jQuery, with local fallback
    = javascript_include_tag 'application'

app/views/layouts/unauthenticated.html.haml
!!! 5
%html
  %head
    %meta{ charset: 'utf-8' }
    %meta{ 'http-equiv' => 'X-UA-Compatible', content: 'IE=edge,chrome=1' }
    %meta{ name: 'viewport', content: 'width=device-width, initial-scale=1' }
    %title
      Forum 2.0
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'head' # Only modernizr, respond.js
    = csrf_meta_tags
  %body.unauthenticated
    .container
      - flash.each do |type, message|
        = alert_box message, context: flash_context(type), dismissible: true unless message.blank?

      .row
        .col-md-6.col-md-offset-3
          .panel.panel-default
            .panel-heading
              %h3.panel-title
                = yield :page_header
            .panel-body
              = yield
    - # Most JS Stuff needs to be at the bottom of the body.
    - #
    - # TODO: Use Google CDN's jQuery, with local fallback
    = javascript_include_tag 'application'